[tool.ruff]
line-length = 132 # 88
indent-width = 4

target-version = "py37"

preview = true

output-format = "concise"

[tool.ruff.lint]
select = [
	"F",
	"E4",
	"E7",
	"E9",
	"W",
	"I",
	# "D",
	"UP",
	"YTT",
	"S",
	"BLE",
	"B",
	"A",
	"COM819",
	"C4",
	"T10",
	"EM",
	"EXE",
	"ISC",
	"ICN",
	"G",
	"PIE",
	"PYI",
	"Q",
	"RSE",
	"RET",
	"SLF",
	"SLOT",
	"SIM",
	"TID",
	"TC",
	"ARG",
	"PGH",
	"PL",
	"TRY",
	"PERF",
	"FURB",
	"LOG",
	"RUF"
]
ignore = [
	"W191",
	"D211",
	"D213",
	"D401",
	"UP004",
	"UP008",
	"UP009",
	"UP010",
	"UP020",
	"UP024",
	"UP030",
	"UP032",
	"UP036",
	"PYI024",
	"PLR09",
	"PLR1702",
	"PLR2004",
	"S324",
	"S404",
	"S603",
	"TRY401",
	"FURB101",
	"FURB167",
	"LOG015",
	"RUF001",
	"RUF002",
	"RUF003",
	"RUF005",
	"RUF012",
	"RUF023"
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "preserve"

indent-style = "tab"

skip-magic-trailing-comma = true
